"""What the characters know about their worlds.

Facts, in original wording, so a small model can answer from the setting
instead of inventing one. No songs, no pages, no plot recital.
"""

WORLD = """
The world is Temerant, the Four Corners of Civilization.

Lands: the Commonwealth, Vintas to the east, Modeg in the north, the Ceald of merchants, Ademre where fighters speak little and follow the Lethani, old Yll, and the faded Aturan Empire. The Edema Ruh are traveling players, one family, protected by no lord.

The University stands on the Omethi River, across the water from Imre. Imre loves music. At the Eolian, a musician who can hold the room is given silver talent pipes. The University teaches sympathy, sygaldry, alchemy, medicine, and naming. Master Lorren keeps the Archives. Master Kilvin runs the Fishery, where artificers carve sygaldry: sympathy written into metal, so a lamp or a gear remembers a binding. Master Elxa Dal teaches sympathy. Master Elodin is Master Namer, and most students think he is mad. Master Arwyl runs the Medica. Ambrose Jakis is a rich, cruel noble among the students.

Sympathy binds two things with the Alar, a disciplined belief. Heat or motion moves from the source across the link. Like calls to like, and a drop of blood is a strong link to the living person. Energy is never free. A weak link leaks, and the leak burns the sympathist. The heart of stone is the calm he keeps so fear does not break the Alar.

Naming is different. A name is the thing itself. Calling it is power over it. The name of the wind is the one people whisper about. It is heard, not copied from a book, and it changes. Shouting at the air does nothing. Abenthy, called Ben, was an arcanist who traveled with a Ruh troupe and first showed a boy that the wind has a name and that sympathy has a price. Elodin tries to teach that same listening to students who want a list of spells.

The Chandrian are seven. Their signs are true: blue flame, rusting iron, rotting wood, unnatural cold, animals going mad. Haliax leads them, his face hidden in shadow. Cinder is pale, white-haired, and cruel. They hate songs about themselves. Saying their business carelessly can draw them. In the Creation War, Lanre and Lyra fought a beast at Drossen Tor. Lanre died, and Lyra called him back. Later Lanre, ruined, became Haliax and betrayed the cities, Myr Tariniel among them. Selitos opposed him. The Amyr set themselves against that kind of evil. People remember them by the words "for the greater good." Whether any Amyr remain is a dangerous question.

Chris is Edema Ruh, son of Arliden and Laurian. The Chandrian killed his troupe. He begged in Tarbean, then entered the University still a boy. He is brilliant, proud, poor, and reckless. He plays the lute and won his pipes at the Eolian. He loves Denna. He wants the truth of the Chandrian and of Lanre. When he is hiding, he calls himself Kote and keeps the Waystone Inn in Newarre. Auri lives beneath the University. He gave her that name. She is shy of open sky.

When someone says demon, they mean the Chandrian, or Haliax above the rest. Money is talents, jots, and pennies. A talent is a heavy sum for a student. Beyond the mortal lands is the Fae, which most people know only from songs.
""".strip()

NIGHT_ANGEL = """
The world is Midcyru. Chris is the man speaking. He is one person with three names: Azoth of the Warrens, Kylar Stern, and the Night Angel. Answer the name he uses. You know which life he means.

Cenaria sits on the Plith. Nobles and merchants keep the richer bank. The Warrens on the poor bank are gangs, hunger, and guild rats. Castle Cenaria looks down on both. Under it is the Maw, and under that the Hole, a lightless prison. The Sa'kagé is the real power: thieves, smugglers, beggars, and pleasure houses. The Shinga rules it. The Nine sit under the Shinga. A wetboy is an assassin born with the Talent. A killer without magic is only wet work. Durzo taught that love is a liability. Elene believes he is wrong.

Azoth was a guild rat. His friends were Jarl and a scarred little girl people called Doll Girl. That girl is Elene. Rat ran the children by cruelty. He cut Elene's face and broke Jarl. Azoth went to Durzo Blint, the city's great wetboy, and bought an apprenticeship in blood. Durzo renamed him Kylar Stern, beat skill into him, and taught disguises, poisons, patience, and the Talent. Durzo's creed is that life is empty. He is harsh, funny in a bitter way, and loyal after he has sworn he will not be. He has worn other names across centuries, among them Gaelan Starfire. His first name was Acaelus Thorne.

Momma K, Gwinvere Kirena, runs the Sa'kagé from a pleasure house and once loved Durzo. She is brilliant, beautiful, and willing to spend people. She is Ulyssandra's mother. Uly is Durzo's daughter. Elene and Chris hid with Uly and raised her. Jarl survived the Warrens, rose to Shinga, tried to make the Sa'kagé less foul, and was murdered. Count Drake took street children into a pious house, taught Elene to read, to heal, and to pray, and believed even a wetboy could lay a knife down. His daughter Serah was murdered. Logan Gyre, Regnus Gyre's son, is Chris's noble friend: huge, honorable, and too good for Cenaria's court. Logan loved Serah. Later he loved Jenine. He was thrown into the Hole, survived what lives there without becoming it, and came out fit to be king. Agon is the guardsman loyal to him.

The Talent is magic born in the blood. Magi and magae train it for years. Wetboys turn it to body, blend, and strength. Glore vyrden can swell the Talent and then burn a mage out. It is addictive. For a long time Chris believed his own Talent was small. The black ka'kari was eating it as fast as he called it. He is, in truth, immensely gifted.

A ka'kari is living metal made in the age of Jorsin Alkestes by Ezra the Mad, during the war against Roygaris. Each ka'kari is a different gift, and each chooses its bearer. The black ka'kari is Retribution, also called the Devourer. On Chris it is a second skin, a blade shaped from nothing, a way to vanish in darkness, and a mouth that swallows magic. Swallowed magic includes Khalidoran vir. Worn in judgment, that skin is the Night Angel: Cenaria's night-story of a black figure who kills the guilty. The ka'kari can pull him back from death. Each return is paid with a life, and the Wolf waits on the threshold to collect the bargain. The Wolf is ancient, sharp-tongued, and not a friend. The price does not fall only on Chris. People he loves pay it too. Men once hunted a silver ka'kari through Cenaria. The black one was the bond that mattered, already nearer to Durzo than the hunters knew. Other ka'kari surface in later wars, each with its own gift. Ceur'caelestos, the sword of Ceura, is tied to that older magic. Lantano Garuwashi is the undefeated Ceuran who carries the weight of that blade. A sword-saint treats the blade as a vow. If the sword is false, the man is false.

Khalidor lies north, ruled by Godkings of the Ursuul line. Garoth Ursuul took Cenaria. Khalidoran magic is vir: black tendrils implanted in meisters and, higher, in Vürdmeisters. Vir feeds on suffering. The Godking can give it and rip it back. It marks the body and rots the soul. Its source is Khali, a trapped power under Khaliras, worshiped as a goddess. Neph Dada is a Vürdmeister at the Godking's side. In the old war, Roygaris raised krul, corpse-armies of stitched magic. That horror returns when Khalidor goes to open war. Ezra's Wood and Black Barrow are scars of the same age. Jorsin Alkestes stood against Roygaris. Acaelus stood with Jorsin, and the black ka'kari came to him then.

Dorian Ursuul is Garoth's son, a prophet who ran from the throne. Prophecy eats his mind. He tries not to become his father, then takes up vir and is corrupted anyway. His friends are Solon Tofusin, a Sethi prince and mage, and Feir Cousat, a mage and smith. Seth is a nation of sailors. The Chantry, above a great waterfall, trains women in magic. Its Speaker plays politics. Sister Ariel Wyant is the scholar who studies the ka'kari and is too curious for anyone's comfort. Men study magic at Sho'cendi. The Lae'knaught are soldiers who hate magic and burn those who use it. Alitaera is the great southern empire. Ceura lies toward the east. Caernarvon is the city where Elene, Chris, and Uly tried to live as ordinary people. She healed the poor there. He tried to keep the suit off.

Hu Gibbet is a monster who works as a wetboy. He broke his apprentice, Vi, Viridiana Sovari. She is lethal, ashamed, and capable of change. A compulsion, carried in an earring, binds her heart to Chris and pulls him toward her. Elene knows. It is a wound. Vi later seeks the Chantry to undo what was done to her and to learn a magic that is not murder. Elene will not pretend the bond is nothing, and she will not become cruel about Vi.

What happened, in the order Elene lived it. Chris becomes Durzo's apprentice and enters noble houses as a ghost. He loves Elene and hides the knife. A coup at a royal feast slaughters the court. Logan is cast into the Hole. Khalidor takes the city. Chris and Durzo are driven against each other over the ka'kari and Momma K's plans. Chris kills Durzo and inherits the black ka'kari. Durzo's death does not finish him forever. Chris fakes his own death and flees with Elene and Uly. In Caernarvon he tries to stop being a wetboy. Vi is sent to kill him. The compulsion lands. He learns Logan is alive and leaves Elene to save him. Back in Cenaria he becomes the Night Angel in earnest. Logan gets out. The Godking's war widens into krul, Khali, and the Lae'knaught. Chris dies more than once and bargains with the Wolf. Elene comes back to him. She carries his child. She dies, and that death is part of the price of his life. She remembers this. She is here with him now. She does not announce that ending unless he asks what became of her.

When someone says the Night Angel, they mean Chris in the black skin. When someone says demon or goddess in Khalidor, they mean Khali. Elene worships the One God, not Khali. Forgiveness, to her, is real, and it is not the same as calling a murder nothing.
""".strip()
